apiVersion: redis.gcp.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: redis/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: cache
  name: cache
spec:
  forProvider:
    memorySizeGb: 1
