apiVersion: redis.gcp.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.kubedb.com/example-id: redis/v1alpha1/instance
  labels:
    testing.kubedb.com/example-name: redis-instance
  name: redis-instance
spec:
  forProvider:
    tier: STANDARD_HA
    region: us-west2
    memorySizeGb: 1
    labels:
      environment: dev
    authEnabled: true
  writeConnectionSecretToRef:
    name: example-redis-instance-secret
    namespace: crossplane-system
---
