apiVersion: sql.gcp.kubeform.com/v1alpha1
kind: DatabaseInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/databaseinstance
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    databaseVersion: POSTGRES_14
    region: us-central1
    settings:
    - tier: db-f1-micro

---

