apiVersion: sql.gcp.kubedb.com/v1alpha1
kind: SSLCert
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/sslcert
  labels:
    testing.upbound.io/example-name: client_cert
  name: client-cert
spec:
  forProvider:
    commonName: client-name
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: sql.gcp.kubedb.com/v1alpha1
kind: DatabaseInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/sslcert
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    databaseVersion: MYSQL_5_7
    settings:
    - tier: db-f1-micro
