apiVersion: compute.gcp.kubeform.com/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allow:
    - protocol: icmp
    - ports:
      - "80"
      - "8080"
      - 1000-2000
      protocol: tcp
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    sourceTags:
    - web

---

apiVersion: compute.gcp.kubeform.com/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider: {}

---

