apiVersion: compute.gcp.kubeform.com/v1alpha1
kind: NetworkPeering
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/networkpeering
  labels:
    testing.upbound.io/example-name: peering1
  name: peering1
spec:
  forProvider:
    network: ${google_compute_network.default.self_link}
    peerNetwork: ${google_compute_network.other.self_link}

---

apiVersion: compute.gcp.kubeform.com/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/networkpeering
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoCreateSubnetworks: "false"

---

apiVersion: compute.gcp.kubeform.com/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/networkpeering
  labels:
    testing.upbound.io/example-name: other
  name: other
spec:
  forProvider:
    autoCreateSubnetworks: "false"

---

