apiVersion: spanner.gcp.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: spanner/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    config: regional-us-central1
    displayName: Test Spanner Instance
    labels:
      foo: bar
    numNodes: 2
